define([
	'./Uri',
    './Base64',
    './Poller',
    './UrlBuilder',
    './SprintfService',
    './UserService',
    './AdminService',
    './AuthService',
    './DashboardService',
    './DashboardMapper',
    './StreamsService',
    './QueryService',
    './ProjectionsService',
    './ProjectionsMapper',
    './MessageService',
    './ProjectionsMonitor',
    './AtomEventsReader'
], function () {});