name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    name: Build UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Packaging
        run: |
          npm install bower@~1.8.4 -g
          bower install
          npm install gulp@~3.8.8 -g
          npm install
          gulp dist
          mv es-dist clusternode-web
          zip -r EventStore.OSS.UI-v${{ steps.release.outputs.version}}.zip clusternode-web
