name: Nightly release
on:
  schedule:
    - cron: '0 2 * * *' # Every day at 2am UTC.
jobs:
  package:
    name: Package UI
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - name: Lookup or create release
        uses: EventStore/Automations/lookup-or-create-release@master
        id: release
        with:
          github-token: ${{ secrets.GH_PAT }}
          build-type: nightly
      - name: Packaging
        run: |
          npm install bower@~1.8.14 -g
          bower install
          npm install gulp@~4.0.0 -g
          npm install
          gulp dist
          mv es-dist clusternode-web
          zip -r EventStore.OSS.UI-v${{ steps.release.outputs.version}}.zip clusternode-web
      - name: Upload Release Asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly-build
          draft: false
          prerelease: true
          token: ${{ secrets.GH_PAT }}
          files: |
            ./EventStore.OSS.UI-v${{ steps.release.outputs.version}}.zip
